### ISSUE TITLE
alias for you

### ISSUE THREAD

**Issue by songleo** [chenxiao-zhao/chenxiao-zhao.github.io#4]
```
alias gad='git add --all'
alias gco='git commit -m'
alias gph='git push'
alias gphall='gad && gco "auto commit" && gph'
```

**Comment by songleo** [comment]
@chenxiao-zhao

**Comment by chenxiao-zhao** [comment]
> ```
> alias gad='git add --all'
> alias gco='git commit -m'
> alias gph='git push'
> alias gphall='gad && gco "auto commit" && gph'
> ```

@songleo Remember the alias you said, thank you friends
